# Generated by Django 3.0.2 on 2020-02-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roshambouser',
            name='guild',
            field=models.CharField(default='', max_length=30),
        ),
    ]
