# Generated by Django 3.0.2 on 2020-02-15 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_roshambouser_guild'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinsInventory',
            fields=[
                ('skin', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('games_lost', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Skins',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('active_skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value', to='accounts.SkinsInventory')),
                ('purchased_skins', models.ManyToManyField(to='accounts.SkinsInventory')),
            ],
        ),
    ]
