# Generated by Django 3.0.2 on 2020-02-13 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_roshambouser_guild'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSkins',
            fields=[
                ('skin', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('games_played', models.PositiveIntegerField(default=0)),
                ('games_won', models.PositiveIntegerField(default=0)),
                ('games_lost', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='roshambouser',
            name='active_skin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PurchasedSkins',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AvailableSkins')),
            ],
        ),
    ]
