# Generated by Django 3.0.3 on 2020-02-17 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_skins_skinsinventory_userstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cash', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='skinsinventory',
            name='price',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
