# Generated by Django 3.0.3 on 2020-02-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user1_ts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='user2_ts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
