# Generated by Django 3.0.3 on 2020-02-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchup', '0002_auto_20200220_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='user1_ts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='user2_ts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
