export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    GETCURRENT_REQUEST: 'USERS_GETCURRENT_REQUEST',
    GETCURRENT_SUCCESS: 'USERS_GETCURRENT_SUCCESS',
    GETCURRENT_FAILURE: 'USERS_GETCURRENT_FAILURE',

    CHANGE_EMAIL_REQUEST: 'USERS_CHANGE_EMAIL_REQUEST',
    CHANGE_EMAIL_SUCCESS: 'USERS_CHANGE_EMAIL_SUCCESS',
    CHANGE_EMAIL_FAILURE: 'USERS_CHANGE_EMAIL_FAILURE',

    CHANGE_PASSWORD_REQUEST: 'USERS_CHANGE_PASSWORD_REQUEST',
    CHANGE_PASSWORD_SUCCESS: 'USERS_CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAILURE: 'USERS_CHANGE_PASSWORD_FAILURE',
}

export const skinsConstants = {
    CHANGE_REQUEST: 'SKINS_CHANGE_REQUEST',
    CHANGE_SUCCESS: 'SKINS_CHANGE_SUCCESS',
    CHANGE_FAILURE: 'SKINS_CHANGE_FAILURE',

    ADD_REQUEST: 'SKINS_ADD_REQUEST',
    ADD_SUCCESS: 'SKINS_ADD_SUCCESS',
    ADD_FAILURE: 'SKINS_ADD_FAILURE',

    GETACTIVE_REQUEST: 'SKINS_GETACTIVE_REQUEST',
    GETACTIVE_SUCCESS: 'SKINS_GETACTIVE_SUCCESS',
    GETACTIVE_FAILURE: 'SKINS_GETACTIVE_FAILURE',

    GETOWNED_REQUEST: 'SKINS_GETOWNED_REQUEST',
    GETOWNED_SUCCESS: 'SKINS_GETOWNED_SUCCESS',
    GETOWNED_FAILURE: 'SKINS_GETOWNED_FAILURE',
}